services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: |
      python --version && \
      python -m pip install --upgrade pip setuptools wheel && \
      python -m pip install --no-build-isolation -r requirements.txt && \
      python manage.py collectstatic --no-input && \
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHON_VERSION
        value: 3.11.9
